var constants = {
    GET_ARTICLE_LIST: "GET_ARTICLE_LIST",
    GET_ARTICLE: "GET_ARTICLE",
    GET_CATEGORY: "GET_CATEGORY",
    SEARCH: "SEARCH",
    CREATE_ARTICLE: "CREATE_ARTICLE",
    REMOVE_ARTICLE: "REMOVE_ARTICLE",
    UPDATE_STATUS_ARTICLE: "UPDATE_STATUS_ARTICLE",
    UPDATE_ARTICLE: "UPDATE_ARTICLE",
    INIT_ARTICLE: "INIT_ARTICLE"
};

module.exports = constants;