var constants = {
    GET_CATEGORY: "GET_CATEGORY",
    ADD_CATEGORY: "ADD_CATEGORY",
    REMOVE_CATEGORY: "REMOVE_CATEGORY",
    UPDATE_STATUS_CATEGORY: "UPDATE_STATUS_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
};

module.exports = constants;