var constants = {
    GET_DETAIL: "GET_DETAIL", // 获取详情
    UPDATE_ID: "UPDATE_ID", // 获取ID
    UPDATE_BOOKEDAT: "UPDATE_BOOKEDAT", // 获取ID
    UPDATE_MOBILE: "UPDATE_MOBILE", // 获取ID
    UPDATE_NAME: "UPDATE_NAME", // 获取ID
    UPDATE_ADDRESS: "UPDATE_ADDRESS", // 获取ID
    UPDATE_TYPE: "UPDATE_TYPE", // 获取ID
    UPDATE_REFUND: "UPDATE_REFUND", // 获取ID
    UPDATE_RETURNMODE: "UPDATE_RETURNMODE" // 获取ID
};

module.exports = constants;
