var constants = {
    UPDATE_SELECTED_MEMBER: "UPDATE_SELECTED_MEMBER",
    INIT_COUPON: "INIT_COUPON",
    UPDATE_COUPON: "UPDATE_COUPON",
    UPDATE_COUPON_KEY: "UPDATE_COUPON_KEY",
    UPDATE_VALID_TIME: 'UPDATE_VALID_TIME'
};

module.exports = constants;
